import Head from 'next/head';
import Button from '@mui/joy/Button';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Button variant="solid" color="neutral">Hello World</Button>
        <h1 className="text-3xl font-bold underline">
          Hello world! asdf
        </h1>

        <div className="h-96"></div>
      </main>
    </>
  )
}
