import Head from 'next/head';
import Button from '@mui/joy/Button';
import Link from 'next/link';
import BackpackOutlinedIcon from '@mui/icons-material/BackpackOutlined';
import PlaceOutlinedIcon from '@mui/icons-material/PlaceOutlined'
import Expandable from '@/components/expandable';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>

        {/* HERO SECTION */}
        <section className="h-auto sm:pt-0 -pt-12 lg:-pt-20 mb-6 flex flex-col bg-gray-50" style={{minHeight: 'calc(100vh - 80px)'}}>
          <div className="min-h-full flex items-center grow flex-col z-10">
                <div className="max-w-6xl mx-auto pt-16 pb-24 w-full grow flex flex-col">
                    <div className="px-8 md:px-16 xl:px-0 grow flex flex-col justify-center" style={{ paddingBottom: '80px'}}>

                        <div className="mb-8 hidden sm:block">
                            <Link className="roudned-full inline-flex space-x-4 rounded-full border border-blue-100 bg-gradient-to-br from-blue-50 to-indigo-100 p-1 pr-2"
                                href="platforms/rural-health-care">
                                <span
                                    className="rounded-full bg-blue-500 px-2.5 py-1 text-xs font-semibold uppercase tracking-wide text-white">
                                    <span>New Release</span>
                                </span>
                                <span className="inline-flex items-center space-x-1 text-sm font-medium text-blue-600">
                                    <span>Introducing Rural Health Care</span>
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                                        aria-hidden="true" className="h-5 w-5">
                                        <path fillRule="evenodd"
                                            d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                            clipRule="evenodd"></path>
                                    </svg>
                                </span>
                            </Link>
                        </div>

                        <h1 className="max-w-4xl font-display text-3xl font-medium tracking-tight text-slate-700 sm:text-7xl">
                            National Broadband Intelligence & <span className="whitespace-nowrap">E-rate</span> Analytics
                        </h1>

                        <p className=" mt-4 max-w-2xl text-base sm:text-xl tracking-tightish text-slate-700">Thousands of schools
                            and
                            libraries
                            are advancing their broadband access and utilizing Universal Service Administrative
                            Company&apos;s Schools and Libraries E-rate Program to help fund these initiatives.</p>

                        <div className="flex gap-3 items-center mt-8">
                          <Button color="neutral" variant="solid" component={Link} href="/blog" style={{ paddingInline: '1.8rem' }}>
                              <span>Get started</span>
                          </Button>
                          <Button color="neutral" variant="plain" component={Link} href="/contact" style={{ paddingInline: '1.8rem' }}>
                              <span>Schedule a demo</span>
                          </Button>
                        </div>
                    </div>
                </div>
            </div>

        </section>

        {/* STATS SECTION */}
        <section className="sm:m-8 xl:m-10 relative mb-12 md:mb-0">
          <div className="max-w-6xl mx-auto px-4 md:px-8 grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-8">
            <div className="rounded-lg md:rounded-3xl bg-gray-100 p-4 md:p-8">
              <BackpackOutlinedIcon className="text-gray-700" style={{ fontSize: 60 }}/>
              <div className="text-2xl text-gray-700 font-medium">$23.4 B+</div>
              <div className="text-sm text-gray-500">of E-rate funding tracked</div>
            </div>
            <div className="rounded-lg md:rounded-3xl bg-gray-100 p-4 md:p-8">
              <BackpackOutlinedIcon className="text-gray-700" style={{ fontSize: 60 }} />
              <div className="text-2xl text-gray-700 font-medium">220 K+</div>
              <div className="text-sm text-gray-500">schools monitored</div>
            </div>
            <div className="rounded-lg md:rounded-3xl bg-gray-100 p-4 md:p-8">
              <BackpackOutlinedIcon className="text-gray-700" style={{ fontSize: 60 }} />
              <div className="text-2xl text-gray-700 font-medium">4 TB+</div>
              <div className="text-sm text-gray-500">of USAC-suggested compliant documents retained</div>
            </div>
            <div className="rounded-lg md:rounded-3xl bg-gray-100 p-4 md:p-8">
              <PlaceOutlinedIcon className="text-gray-700" style={{ fontSize: 60 }} />
              <div className="text-2xl text-gray-700 font-medium">50 K+ Miles</div>
              <div className="text-sm text-gray-500">of fiber routes deployed</div>
            </div>
          </div>
        </section>

        {/* E-RATE SECTION */}
        <section className="sm:m-8 xl:m-10 mb-12 md:mb-0">
          <div className="max-w-6xl mx-auto px-4 md:px-8">
              <div
                  className="rounded-lg sm:rounded-3xl bg-slate-100 flex flex-col-reverse md:grid md:grid-cols-2 md:gap-4 overflow-hidden">
                  <div className="py-0 pr-20 md:pr-0 -md:mx-8 md:mt-16 flex">
                      <img src="/erate-dashboard-safari-dark.png" className="pointer-events-none w-full" style={{
                        borderTopRightRadius: '7px',
                        boxShadow: '8px -8px 15px 0px rgb(0 0 0 / 10%), 4px -4px 11px 0px rgb(0 0 0 / 10%)'
                      }}></img>
                  </div>
                  <div className="flex flex-col justify-center p-8 md:py-0 md:px-16 gap-4">
                      <div className="text-xl uppercase text-slate-600">E-rate</div>
                      <div className="text-4xl text-slate-700 font-semibold">Keep track of all your E-rate data better than you
                          ever have.</div>
                      <div className="text-lg text-slate-500">Whether you are a small private school or a large internet provider,
                          BroadbandHub gathers all of your E-rate needs into one dashboard.</div>
                      <div>
                          <Link href="/erate" className="font-medium text-blue-500 flex items-center gap-1">
                            <span>Learn more about our E-rate platform</span>
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                                aria-hidden="true" className="h-5 w-5">
                                <path fillRule="evenodd"
                                    d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                    clipRule="evenodd"></path>
                            </svg>
                          </Link>
                      </div>
                  </div>
              </div>
          </div>
      </section>

        {/* RURAL HEALTH CARE SECTION */}
        <section className="sm:m-8 xl:m-10 mb-12 md:mb-0">
          <div className="max-w-6xl mx-auto px-4 md:px-8">
              <div
                  className="rounded-lg sm:rounded-3xl bg-blue-500 flex flex-col md:grid md:grid-cols-2 md:gap-4 overflow-hidden">
                  <div className="flex flex-col justify-center p-8 md:py-0 md:px-16 gap-4">
                      <div className="flex items-center gap-3">
                          <div className="text-xl uppercase text-slate-100">Rural Health Care</div>
                          <div className="bg-white/[.15] text-white px-2 rounded-full text-sm font-semibold">BETA</div>
                      </div>
                      <div className="text-4xl text-white font-semibold">The first comprehensive Rural Health Care web platform
                      </div>
                      <div className="text-lg text-slate-200">Our newest platform is now in beta mode. Join us as we pioneer the
                          best tool for tracking and analyzing RHC data.</div>
                      <div>
                          <Link href="/rural-health-care" className="!text-white font-medium flex items-center gap-1">
                            <span>Learn more about our RHC platform</span>
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                                aria-hidden="true" className="h-5 w-5">
                                <path fillRule="evenodd"
                                    d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                    clipRule="evenodd"></path>
                            </svg>
                          </Link>
                      </div>
                  </div>
                  <div className="py-0 pl-20 md:pl-0 -md:mx-8 md:mt-16 flex">
                      <img src="/rhc-dashboard-safari-dark.png" className="pointer-events-none w-full"></img>
                  </div>
              </div>
          </div>
      </section>

        {/* MAPPING SECTION */}
        <section className="sm:m-8 xl:m-10 mb-12 md:mb-0">
          <div className="max-w-6xl mx-auto px-4 md:px-8">
              <div className="rounded-lg sm:rounded-3xl bg-slate-100"
              style={{
                backgroundImage: `linear-gradient(to top,rgba(255,255,255,.3),rgba(255,255,255,.7)),url('/map-gray-large.png')`
              }}>

                  <div
                      className="flex flex-col justify-center items-start md:items-center px-4 md:px-16 gap-4 py-8 md:py-28 max-w-2xl mx-auto">
                      <div className="text-xl uppercase text-slate-600">Mapping and Target Automation</div>
                      <div className="text-4xl text-slate-700 font-semibold md:text-center">The most advanced E-rate and Rural
                          Health
                          Care map on
                          the internet.</div>
                      <div className="text-lg text-slate-500 md:text-center">Explore broadband data in a new medium. Our powerful,
                          in-web mapping software allows you to compare multiple geographical datasets to better understand
                          broadband data.</div>
                      <div>
                          <Link href="/mapping" className="flex items-center gap-1 font-medium">
                            <span>Learn more about Mapping</span>
                            <span className="hidden md:inline">&nbsp;and Target Automation</span>
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                                aria-hidden="true" className="h-5 w-5">
                                <path fillRule="evenodd"
                                    d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                    clipRule="evenodd"></path>
                            </svg>
                          </Link>
                      </div>
                  </div>

              </div>
          </div>
      </section>

        {/* DOCUMENT LOCKER SECTION */}
        <section className="sm:m-8 xl:m-10 mb-12 md:mb-0">
          <div className="max-w-6xl mx-auto px-4 md:px-8">
              <div className="rounded-lg sm:rounded-3xl bg-blue-500">
                  <div
                      className="flex flex-col justify-center items-start md:items-center px-4 md:px-16 gap-4 py-8 md:py-28 max-w-2xl mx-auto">
                      <div className="text-xl uppercase text-white/80">Document Locker</div>
                      <div className="text-4xl text-white font-semibold md:text-center">Automated document retention for your
                          compliance requirements.</div>
                      <div className="text-lg text-white/70 md:text-center">Be better prepared for audits with secure, reliable,
                          USAC-suggested compliant document cloud storage.</div>
                      <div className="pt-4">
                          <Link href="/document-locker" className="!text-white flex items-center gap-1 font-medium">
                            <span>Learn more about Document Locker</span>
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                                aria-hidden="true" className="h-5 w-5">
                                <path fillRule="evenodd"
                                    d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                    clipRule="evenodd"></path>
                            </svg>
                          </Link>
                      </div>
                  </div>
              </div>
          </div>
      </section>

        {/* FAQ SECTION */}
        <section className="sm:m-8 xl:m-10 mb-12 md:mb-0">
          <div className="max-w-4xl mx-auto px-4 py-12 md:py-24 md:px-8">

              <div className="text-center text-4xl text-slate-700 font-semibold mb-8 md:mb-16">Frequenty asked questions</div>

              <div className="rounded-lg sm:rounded-3xl bg-gray-100 p-6 md:p-12">
                  
                  <Expandable title="Can I trial BroadbandHub before paying?">
                      Yes, we want you to try Suggestr on your store for 30 days, free of charge, before committing. The analytics dashboard
                      embedded within your Shopify Admin will tell you exactly how much addition upsells and cross-sells revenue Suggestr has
                      generated for your brand.
                  </Expandable>
                  <Expandable title="Can I trial BroadbandHub before paying?">
                      Yes, we want you to try Suggestr on your store for 30 days, free of charge, before committing. The analytics
                      dashboard
                      embedded within your Shopify Admin will tell you exactly how much addition upsells and cross-sells revenue Suggestr
                      has
                      generated for your brand.
                  </Expandable>
                  <Expandable title="Can I trial BroadbandHub before paying?">
                      Yes, we want you to try Suggestr on your store for 30 days, free of charge, before committing. The analytics
                      dashboard
                      embedded within your Shopify Admin will tell you exactly how much addition upsells and cross-sells revenue Suggestr
                      has
                      generated for your brand.
                  </Expandable>
                  <Expandable title="Can I trial BroadbandHub before paying?">
                      Yes, we want you to try Suggestr on your store for 30 days, free of charge, before committing. The analytics
                      dashboard
                      embedded within your Shopify Admin will tell you exactly how much addition upsells and cross-sells revenue Suggestr
                      has
                      generated for your brand.
                  </Expandable>

              </div>
          </div>
      </section>

        {/* CALL TO ACTION SECTION */}

      </main>
    </>
  )
}
